[keys.alice]
path = "keys/alice.pub"
key_type = "rsa"

[keys.bob]
path = "keys/bob.pub"
key_type = "rsa"

[[steps]]
name = "clone"
expected_products = ["CREATE *"]
pubkeys = ["alice", "bob"]

[[steps]]
name = "update"
expected_materials = [
    "MATCH src/* WITH PRODUCTS FROM clone",
    "MATCH pyproject.toml WITH PRODUCTS FROM clone",
    "ALLOW README.md",
    "DISALLOW *",
]
expected_products = [
    "MODIFY pyproject.toml",
    "MODIFY src/main.py",
    "MATCH * WITH MATERIALS FROM update",
    "ALLOW README.md",
    "DISALLOW *",
]
pubkeys = ["alice", "bob"]

[[steps]]
name = "build"
expected_materials = [
    "MATCH src/* WITH PRODUCTS FROM update",
    "MATCH pyproject.toml WITH PRODUCTS FROM update",
    "ALLOW README.md",
    "DISALLOW *",
]
expected_products = [
    "CREATE test_project-0.0.2-py3-none-any.whl",
    "DISALLOW *",
]
pubkeys = ["alice"]
